#!/usr/bin/env bash

U=$(id -nu)
G=$(id -ng)

NAME="el7cvmfs"
if [[ "${1}" == "sandbox" ]]; then
  shift
  DO_SANDBOX="--sandbox --fix-perms"
  NAME="${NAME}_sandbox"
fi
[[ -e "${NAME}" ]] && rm -f "${NAME}"

sudo -E singularity build "${DO_SANDBOX}" "${NAME}" Singularity

[[ -n "${DO_SANDBOX}" ]] && sudo chown -R ${U}:${G} "${NAME}"
sudo chown -R ${U}:${G} "${SINGULARITY_CACHEDIR:-${HOME}/.singularity/cache}"
